### ISSUE TITLE
Writing long FOR loop, the content is getting hidden if indentation the is given to the code while dragging for python and in C.

### ISSUE THREAD

**Issue by Karan-21** [uofa-Parsons-hub/H5P.ParsonsPuzzle#42]
![image](https://user-images.githubusercontent.com/64781870/107458189-83340d80-6ba3-11eb-9093-11cd6055f157.png)

**Comment by cheryl-pope** [comment]
This is intentional - the yellow box is sized to the code + required indentation.  Code lines will only hide if the students have indented them incorrectly.
